In [1]:
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score
# import datawig

In [2]:
df2 = pd.read_json('./dataSet_Culture_06102023-POINT.json')

In [3]:
df2 = df2.drop(columns=['type_culture_name', 'soil_id'])

In [4]:
print(df2.isnull().sum())
print(df2.shape)
# df2['type_culture_name'] = df2['type_culture_name'].replace(np.NaN, 'nodataculturetype')

polygon              0
indextype            0
averagevalue         0
Analysis Date        0
year contour         0
elevation_contour    0
district_name        0
soil_name            0
culture_name         0
dtype: int64
(22982, 9)

In [5]:
df2['Analysis Date'].info

<bound method Series.info of 0        2020-06-04
1        2020-08-03
2        2020-09-02
3        2021-04-10
4        2021-05-05
            ...
22977    2022-05-08
22978    2022-06-07
22979    2022-07-02
22980    2022-08-01
22981    2022-10-05
Name: Analysis Date, Length: 22982, dtype: object>

In [6]:
df2['Analysis Date'] = pd.to_datetime(df2['Analysis Date'])

In [7]:
df2['x_coordinate'] = df2['polygon'].apply(lambda coord: coord['x'])
df2['y_coordinate'] = df2['polygon'].apply(lambda coord: coord['y'])

# If you want to drop the original 'polygon' column
df2 = df2.drop(columns=['polygon'])

In [8]:
df2['combined'] = df2['x_coordinate'].astype(str) + '_' + df2['y_coordinate'].astype(str) + '_' + df2['year contour'].astype(str)

# Assign unique ID based on the grouped column
df2['field_id'] = df2.groupby('combined').ngroup() + 1

# Drop the combined column
df2 = df2.drop(columns=['combined'])

df2

,indextype,averagevalue,Analysis Date,year contour,elevation_contour,district_name,soil_name,culture_name,x_coordinate,y_coordinate,field_id
0,NDVI,0.217,2020-06-04,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
1,NDVI,0.215,2020-08-03,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
2,NDVI,0.150,2020-09-02,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
3,NDVI,0.052,2021-04-10,2021,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,987
4,NDVI,0.056,2021-05-05,2021,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,987
...,...,...,...,...,...,...,...,...,...,...,...
22977,VARI,0.055,2022-05-08,2022,672,Yssyk-Ata district,"Сероземно-луговые, местами солончаковатые",Кукуруза,74.890000,42.975269,752
22978,VARI,0.072,2022-06-07,2022,672,Yssyk-Ata district,"Сероземно-луговые, местами солончаковатые",Кукуруза,74.890000,42.975269,752
22979,VARI,-0.002,2022-07-02,2022,672,Yssyk-Ata district,"Сероземно-луговые, местами солончаковатые",Кукуруза,74.890000,42.975269,752
22980,VARI,0.006,2022-08-01,2022,672,Yssyk-Ata district,"Сероземно-луговые, местами солончаковатые",Кукуруза,74.890000,42.975269,752
22981,VARI,-0.007,2022-10-05,2022,672,Yssyk-Ata district,"Сероземно-луговые, местами солончаковатые",Кукуруза,74.890000,42.975269,752

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22982 entries, 0 to 22981
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   indextype          22982 non-null  object
 1   averagevalue       22982 non-null  float64
 2   Analysis Date      22982 non-null  datetime64[ns]
 3   year contour       22982 non-null  int64
 4   elevation_contour  22982 non-null  int64
 5   district_name      22982 non-null  object
 6   soil_name          22982 non-null  object
 7   culture_name       22982 non-null  object
 8   x_coordinate       22982 non-null  float64
 9   y_coordinate       22982 non-null  float64
 10  field_id           22982 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(3), object(4)
memory usage: 1.9+ MB

In [10]:
df2[df2['field_id'] == 986]

,indextype,averagevalue,Analysis Date,year contour,elevation_contour,district_name,soil_name,culture_name,x_coordinate,y_coordinate,field_id
0,NDVI,0.217,2020-06-04,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
1,NDVI,0.215,2020-08-03,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
2,NDVI,0.150,2020-09-02,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
14,NDWI,-0.200,2020-06-04,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
15,NDWI,-0.190,2020-08-03,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
16,NDWI,-0.150,2020-09-02,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
28,SAVI,0.326,2020-06-04,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
29,SAVI,0.322,2020-08-03,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
30,SAVI,0.225,2020-09-02,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
42,VARI,0.063,2020-06-04,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986
43,VARI,0.104,2020-08-03,2020,1544,Kemin district,Горные светло-каштановые,Картофель,76.095454,42.728343,986

In [11]:
# Apply label encoding
for column in df2.columns:
    le = LabelEncoder()
    df2[column + '_encoded'] = le.fit_transform(df2[column])

print(df2)

      indextype  averagevalue Analysis Date  year contour  elevation_contour  \
0          NDVI         0.217    2020-06-04          2020               1544
1          NDVI         0.215    2020-08-03          2020               1544
2          NDVI         0.150    2020-09-02          2020               1544
3          NDVI         0.052    2021-04-10          2021               1544
4          NDVI         0.056    2021-05-05          2021               1544
...         ...           ...           ...           ...                ...
22977      VARI         0.055    2022-05-08          2022                672
22978      VARI         0.072    2022-06-07          2022                672
22979      VARI        -0.002    2022-07-02          2022                672
22980      VARI         0.006    2022-08-01          2022                672
22981      VARI        -0.007    2022-10-05          2022                672

            district_name                                  soil_name  \
0          Kemin district                   Горные светло-каштановые
1          Kemin district                   Горные светло-каштановые
2          Kemin district                   Горные светло-каштановые
3          Kemin district                   Горные светло-каштановые
4          Kemin district                   Горные светло-каштановые
...                   ...                                        ...
22977  Yssyk-Ata district  Сероземно-луговые, местами солончаковатые
22978  Yssyk-Ata district  Сероземно-луговые, местами солончаковатые
22979  Yssyk-Ata district  Сероземно-луговые, местами солончаковатые
22980  Yssyk-Ata district  Сероземно-луговые, местами солончаковатые
22981  Yssyk-Ata district  Сероземно-луговые, местами солончаковатые

      culture_name  x_coordinate  y_coordinate  ...  averagevalue_encoded  \
0        Картофель     76.095454     42.728343  ...                   789
1        Картофель     76.095454     42.728343  ...                   787
2        Картофель     76.095454     42.728343  ...                   722
3        Картофель     76.095454     42.728343  ...                   624
4        Картофель     76.095454     42.728343  ...                   628
...            ...           ...           ...  ...                   ...
22977     Кукуруза     74.890000     42.975269  ...                   627
22978     Кукуруза     74.890000     42.975269  ...                   644
22979     Кукуруза     74.890000     42.975269  ...                   570
22980     Кукуруза     74.890000     42.975269  ...                   578
22981     Кукуруза     74.890000     42.975269  ...                   565

       Analysis Date_encoded  year contour_encoded  elevation_contour_encoded  \
0                          3                     0                        214
1                          7                     0                        214
2                          9                     0                        214
3                         13                     1                        214
4                         15                     1                        214
...                      ...                   ...                        ...
22977                     26                     2                         67
22978                     28                     2                         67
22979                     30                     2                         67
22980                     31                     2                         67
22981                     35                     2                         67

       district_name_encoded  soil_name_encoded  culture_name_encoded  \
0                          2                  4                     2
1                          2                  4                     2
2                          2                  4                     2
3                          2                  4                     2
4                          2                  4                     2
...                      ...                ...                   ...
22977                      6                  9                     4
22978                      6                  9                     4
22979                      6                  9                     4
22980                      6                  9                     4
22981                      6                  9                     4

       x_coordinate_encoded  y_coordinate_encoded  field_id_encoded
0                       345                    11               985
1                       345                    11               985
2                       345                    11               985
3                       345                    11               986
4                       345                    11               986
...                     ...                   ...               ...
22977                   266                   257               751
22978                   266                   257               751
22979                   266                   257               751
22980                   266                   257               751
22981                   266                   257               751

[22982 rows x 22 columns]

In [12]:
# df2 = df2.drop(columns=['indextype', 'district_name', 'soil_name', 'culture_name'])

In [13]:
correlation_matrix = df2[df2['field_id'] == 986].corr()

print(correlation_matrix)

ValueError: could not convert string to float: 'NDVI'

In [ ]:
import numpy as np

# Extract the day of the year
df2['DayOfYear'] = df2['Analysis Date'].dt.dayofyear

# Determine the 10-day quarter based on the day of the year
df2['Quarter'] = np.ceil(df2['DayOfYear'] / 10).astype(int)

# Drop the temporary 'DayOfYear' column
df2 = df2.drop(columns=['DayOfYear'])

In [ ]:
df2